title: James Blunt

'Back to Bedlam':
    'High':
        id: OfFrxv-wsG8
        live: St James's Church, Dingle, Ireland, 2005
    "You're Beautiful":
        id: jrMaxqB2tro
        live: St James's Church, Dingle, Ireland, 2005
    'Wisemen':
        id: gWWP4VFb5iw
        live: St James's Church, Dingle, Ireland, 2005
    'Goodbye My Lover':
        id: NtAQ_6_a22U
        live: St James's Church, Dingle, Ireland, 2005
    'Tears and Rain':
        id: vnBHrH7QWfk
        live: St James's Church, Dingle, Ireland, 2005
    'Out of My Mind':
        id: cKsKPJAo7ac
        live: BBC Elstree Centre, Borehamwood, England, 2005
    'So Long, Jimmy':
        id: 6rZivIRE5ZM
        live: St James's Church, Dingle, Ireland, 2005
    'Billy':
        id: nsMRwbPfX6Y
        live: St James's Church, Dingle, Ireland, 2005
    'Cry':
        id: tEjswCcKrvU
        live: St James's Church, Dingle, Ireland, 2005
    'No Bravery':
        id: P50LTp3E8po
        live: St James's Church, Dingle, Ireland, 2005
    'Sugar Coated':
        id: TXyQvBr9WdI
        live: St James's Church, Dingle, Ireland, 2005
        source: B-side of "High"
    'Fall at Your Feet':
        id: u4fRt0O3J-M
        live: St James's Church, Dingle, Ireland, 2005
        source: B-side of "You're Beautiful"
    'In a Little While':
        id: ZzuvhsI2OmQ
        cover: U2
        live: Radio 1 Jo Whiley Session
        source: B-side of "High"
    'Where Is My Mind?':
        id: x-P9LsOhvrc
        live: St James's Church, Dingle, Ireland, 2005
        source: B-side of "High"
    'Butterfly':
        id: 2kUuErfN5Go
        source: B-side of "High"
    'Close Your Eyes':
        id: Hfs5olExwxc
        source: B-side of "Goodbye My Lover"
    'I Want You':
        id: czCwC0BrMc8
        cover: Bob Dylan
        source: '"Listen to Bob Dylan: A Tribute" album'
    "If There's Any Justice":
        id: fmR5-1vqPR0
        cover: Lemar
        source: '"Radio 1''s Live Lounge" album'
    'Rocky Raccoon':
        id: SRWKNLDZiHI
        cover: The Beatles

'All the Lost Souls':
    '1973':
        id: g8vHqU9giRY
    'One of the Brightest Stars':
        id: 6caQKKnQfR0
        live: iTunes Live London Festival, 2008
    "I'll Take Everything":
        id: 3loQ4SEDico
    'Same Mistake':
        id: rQKGjkP_hLo
    'Carry You Home':
        id: zNXoFURj7Ow
        live: iTunes Live London Festival, 2008
    'Give Me Some Love':
        id: WX98eRU1RPU
        live: iTunes Live London Festival, 2008
    'I Really Want You':
        id: 4eapcyJKiNo
        live: iTunes Live London Festival, 2008
    'Shine On':
        id: 0gS6CBqm4eQ
    'Annie':
        id: bNvp7qX24kw
    "I Can't Hear the Music":
        id: gnUZIMrlPFY
    'Love, Love, Love':
        id: 5KnLRoz3kL8
        source: deluxe edition
    'Cuz I Love You':
        id: Z3ZG2STx0UA
        cover: Slade
        live: Glastonbury, 2008
        source: deluxe edition
    'Young Folks':
        id: ywC9OCy1q6E
        live: Jo While Live Lounge, 2007
        source: deluxe edition
    'Breakfast in America':
        id: d6bGptrGyRA
        cover: Supertramp
        live: unknown place
        source: deluxe edition
    'Primavera in anticipo (It Is My Song)':
        id: DJj_9i577Go
        source: single by Laura Pausini
    'Je réalise':
        id: 4ubkK4O4Sf8
        source: single by Sinik
    'Dear Katie':
        id: UOIpalbOThc
        source: B-side of "1973"
    'So Happy':
        id: GNaMgweEr9I
        source: B-side of "1973"

'Some Kind of Trouble':
    'Stay the Night':
        id: VjXQc0qplWk
    'Dangerous':
        id: ffuPKpaLjLg
    'Best Laid Plans':
        id: eSee1DNyMyg
    'So Far Gone':
        id: QfiJ4CySJSE
        live: Metropolis Studios, London, 2010
    'No Tears':
        id: gQPPztimPXs
    'Superstar':
        id: GL9esIRRyCk
    'These Are the Words':
        id: uCYr7Q2EVio
    'Calling Out Your Name':
        id: Ej13DeRaaOw
    'Heart of Gold':
        id: v-Xcyv2JAmg
    "I'll Be Your Man":
        id: IUkLOUNxP8A
    'If Time Is All I Have':
        id: riz4AA35hD4
        live: Metropolis Studios, London, 2010
    'Turn Me On':
        id: qXURanouVoU
    'There She Goes Again':
        id: b7No2SF3V-8
        source: digital edition bonus
    'Into the Dark':
        id: 86LYA4GK9Fc
        source: digital edition bonus
    'This Love Again':
        id: 3-1te-33RWI
        source: B-side of "I'll Be Your Man"
    'Why Do I Fall':
        id: pJlGGAiqDa8
        source: '"Titeuf" soundtrack'

'Moon Landing':
    'Face the Sun':
        id: qSg-sqnINd0
    'Satellites':
        id: XyLQjMC2Q38
    'Bonfire Heart':
        id: g1j1qwQQ8-Q
    'Heart to Heart':
        id: CsFb661EXsI
    'Miss America':
        id: YTsIt4JQXHs
    'The Only One':
        id: d_kLQo6Rv6g
    'Sun on Sunday':
        id: qT9SPeyNe8w
    'Bones':
        id: nSti9yvsQLI
    'Always Hate Me':
        id: zKBGTbd-epM
    'Postcards':
        id: DB7jsjt4Uec
    'Blue on Blue':
        id: MQsdrs78MSo
    'Smoke Signals':
        id: TOQDppcjB-c
        source: Apollo Edition
    'When I Find Love Again':
        id: yEl5m8eELeI
        source: Apollo Edition
    'Telephone':
        id: ydcN_-FlLnA
        source: Apollo Edition
    'Kiss This Love Goodbye':
        id: neV-1_KYgeY
        source: Apollo Edition
    'Hollywood':
        id: j6em8Baa5Dg
        source: Apollo Edition
    'Breathe':
        id: PBfb_C1vb3I
        source: Apollo Edition
    'Trail of Broken Hearts':
        id: OyAqb6aUUd4
        source: Apollo Edition
    'Working It Out':
        id: 6pu9jeiJwUg
        source: Apollo Edition
    "Next Time I'm Seventeen":
        id: E6xcl3NL8RU
        source: B-side of "Bonfire Heart"
    'Heroes':
        id: yKR5CHbifEo
        source: B-side of "Bonfire Heart"
    "I Guess That's Why They Call It the Blues":
        id: 3j9YJo9IdFQ
        cover: Elton John
        source: 'BBC Radio 2: Sounds of the 80s'

'The Afterlove':
    'Love Me Better':
        id: RFHHEac83B8
    'Bartender':
        id: QAyjgG0-Deg
    'Lose My Number':
        id: llvGsoi4xwQ
    "Don't Give Me Those Eyes":
        id: yJZh9NWdXrE
    'Someone Singing Along':
        id: _JfGdDtBstQ
        live: Sacramento, California, 2017
    'California':
        id: Wgs2ahWHjHQ
    'Make Me Better':
        id: N12lUcqYUL0
    'Time of Our Lives':
        id: QeIK7OeoKFc
    'Heartbeat':
        id: egwr4PNDBQM
    'Paradise':
        id: UliRcD0FEAI
    "Courtney's Song":
        id: D-cPwHBqG-w
        source: extended version
    '2005':
        id: orS6b4YQGPs
        source: extended version
    'Over':
        id: qBeR8byJy3w
        source: extended version
    'OK':
        id: 9kxQ7GFngTA
        live: Ed Sheeran Tour, Tampa, 2017
        source: extended version
    'Bridge over Troubled Water':
        id: _vBCAwHXD3o
        cover: Simon & Garfunkel
        source: Artists for Grenfell Tower charity single
    'Melody':
        id: hXrtQjiyfBg
        source: '"Alive and Feeling Fine" album by Lost Frequencies'
    'Walk Away':
        id: q_5KPQR1Lrs
        source: '"Sticker on My Suitcase" album by Alle Farben'

'Once Upon a Mind':
    'The Truth':
        id: wc4RUrA05LU
    'Cold':
        id: 6--sRjqlRaw
    'Champions':
        id: HOkSkTIQqQM
    'Monsters':
        id: DTFbGcnl0po
    'Youngster':
        id: BBW1JLJpV1o
    '5 Miles':
        id: dyPc7UHLXws
    'How It Feels to Be Alive':
        id: Okvmo4wsCs8
    'I Told You':
        id: vNnq0xphtd4
    'Halfway':
        id: E2GqYX9-UBA
    'Stop the Clock':
        id: wmaCCwiJ54U
    'The Greatest':
        id: DJVINNsf_QE
    'Should I Give It All Up':
        id: 1JtlfpXRMAE
        source: Time Suspended edition
    'Happier':
        id: 4X6mrJbtmX4
        source: Time Suspended edition
    'Love Under Pressure':
        id: iW39_R-JZl0
        source: '"The Stars Beneath My Feet (2004–2021)" compilation album'
    'Adrenaline':
        id: gQ6CYMMU_Qk
        source: '"The Stars Beneath My Feet (2004–2021)" compilation album'
    'Unstoppable':
        id: sFRtMtsFHRA
        source: '"The Stars Beneath My Feet (2004–2021)" compilation album'

'Who We Used to Be':
    'Saving a Life':
        id: GuPWq-d6U0U
    'Some Kind of Beautiful':
        id: RI0HJhmhJiQ
    'Beside You':
        id: O4ce48whOo0
    'Last Dance':
        id: 1OAG4-eT9Gk
    'All the Love That I Ever Needed':
        id: StahDvuzb5w
    'The Girl That Never Was':
        id: NO0W5o5VWYE
    'Cold Shoulder':
        id: --hVkcGyWlI
    "I Won't Die with You":
        id: DgMcum5M-0Q
    'Dark Thought':
        id: sFClYIicGOw
    'Glow':
        id: pI2otpEzFBI
    'Confetti and Roses':
        id: CzteHhr7_TQ
        source: deluxe edition
    'Care a Little Less':
        id: depku1_U_dQ
        source: deluxe edition
    'A Thousand Lives':
        id: McxM4cCpbrc
        source: deluxe edition
    "When You're Gone":
        id: BE34fuedcDg
        source: deluxe edition
    "Can't Forget You":
        id: todcvHFHn3c
        source: single by James Carter

