country: PL
title: James Blunt

'Back to Bedlam':
    'High':
        id: 64sWhkynp_c
    "You're Beautiful":
        id: yJYcrYnAEoU
    'Wisemen':
        id: _clmRy1mqoQ
    'Goodbye My Lover':
        id: 8AOvnzBQBYM
    'Tears and Rain':
        id: pVYIKhcgTq4
    'Out of My Mind':
        id: aQuM1ArilYY
    'So Long, Jimmy':
        id: fUYJ55Te3G0
    'Billy':
        id: zyAaZcO9W90
    'Cry':
        id: oCXMq3JPEm8
    'No Bravery':
        id: MYSU8pSXLcc
    'Dancing Days':
        id: 8o3qKiwjNtM
        source: 20th anniversary edition
    'Standing All Alone':
        id: CL2etiP4K-o
        source: 20th anniversary edition
    'Sugar-Coated':
        id: YeWfePCXcAk
        source: B-side of "High"
    'Fall at Your Feet':
        id: J4tk66HGD9Y
        cover: Crowded House
        source: B-side of "You're Beautiful"
    'In a Little While':
        id: ZzuvhsI2OmQ
        cover: U2
        live: Radio 1 Jo Whiley Session, 2005
        source: B-side of "High"
    'Butterfly':
        id: -TSjnud8tzA
        source: B-side of "High"
    'Close Your Eyes':
        id: svjmSQTOO6Y
        source: B-side of "Goodbye My Lover"
    'Where Is My Mind?':
        id: P0nyycsDjtA
        cover: Pixies
        live: La Cigale, Paris, 2005
        source: B-side of "Goodbye My Lover"
    'I Want You':
        id: czCwC0BrMc8
        cover: Bob Dylan
        source: '"Listen to Bob Dylan: A Tribute" album'
    "If There's Any Justice":
        id: fmR5-1vqPR0
        cover: Lemar
        live: Radio 1 Jo Whiley Live Lounge, 2006
        source: '"Radio 1''s Live Lounge" album'
    'Rocky Raccoon':
        id: SRWKNLDZiHI
        cover: The Beatles

'All the Lost Souls':
    '1973':
        id: g8vHqU9giRY
    'One of the Brightest Stars':
        id: qRQ0uBVH-10
    "I'll Take Everything":
        id: 3loQ4SEDico
    'Same Mistake':
        id: 2K_EYasST78
    'Carry You Home':
        id: hB5dDyZYNC0
    'Give Me Some Love':
        id: Cx3E0PaLJbs
    'I Really Want You':
        id: 69vlIQ7Zous
    'Shine On':
        id: 0gS6CBqm4eQ
    'Annie':
        id: bNvp7qX24kw
    "I Can't Hear the Music":
        id: gnUZIMrlPFY
    'Love, Love, Love':
        id: 5KnLRoz3kL8
        source: deluxe edition
    'Cuz I Love You':
        id: y_IJXtYrHyE
        cover: Slade
        live: Glastonbury, 2008
        source: deluxe edition
    'Breakfast in America':
        id: d6bGptrGyRA
        cover: Supertramp
        live: Hammersmith Apollo, London, 2008
        source: deluxe edition
    'Dear Katie':
        id: aKx59uipW0o
        source: B-side of "1973"
    'So Happy':
        id: GNaMgweEr9I
        source: B-side of "1973"
    'Young Folks':
        id: _e-_sLxJ1WI
        cover: Peter Bjorn and John
        live: Radio 1 Jo Whiley Live Lounge, 2007
        source: B-side of "Carry You Home"
    'Je réalise':
        id: 4ubkK4O4Sf8
        source: single by Sinik
    'Primavera in anticipo (It Is My Song)':
        id: 1L2NMDgDpbE
        source: single by Laura Pausini
    'Everybody Hurts':
        id: Jp947NNH6Is
        cover: R.E.M.
        source: Helping Haiti charity single

'Some Kind of Trouble':
    'Stay the Night':
        id: VjXQc0qplWk
    'Dangerous':
        id: gQgTOpGE06Y
    'Best Laid Plans':
        id: eSee1DNyMyg
    'So Far Gone':
        id: zSgsTLZphTU
    'No Tears':
        id: gQPPztimPXs
    'Superstar':
        id: GL9esIRRyCk
    'These Are the Words':
        id: uCYr7Q2EVio
    'Calling Out Your Name':
        id: Ej13DeRaaOw
    'Heart of Gold':
        id: v-Xcyv2JAmg
    "I'll Be Your Man":
        id: 6T3-Q5vdMYc
    'If Time Is All I Have':
        id: GcQq0E5SpHY
    'Turn Me On':
        id: qXURanouVoU
    'There She Goes Again':
        id: sTLUj_Ogc8I
        source: Amazon edition bonus
    'Into the Dark':
        id: WhKzNrA4n48
        source: iTunes edition bonus
    'This Love Again':
        id: 3-1te-33RWI
        source: Japanese edition bonus
    'Why Do I Fall':
        id: pJlGGAiqDa8
        source: '"Titeuf" soundtrack'

'Moon Landing':
    'Face the Sun':
        id: qSg-sqnINd0
    'Satellites':
        id: jaYpfUISfik
    'Bonfire Heart':
        id: oVIaL5CovIU
    'Heart to Heart':
        id: -Y2qAiwSm7I
    'Miss America':
        id: YTsIt4JQXHs
    'The Only One':
        id: d_kLQo6Rv6g
    'Sun on Sunday':
        id: qT9SPeyNe8w
    'Bones':
        id: nSti9yvsQLI
    'Always Hate Me':
        id: zKBGTbd-epM
    'Postcards':
        id: 1thh7YPSNo8
    'Blue on Blue':
        id: UkN0Huf2wus
    'Telephone':
        id: ydcN_-FlLnA
        source: deluxe edition
    'Kiss This Love Goodbye':
        id: neV-1_KYgeY
        source: deluxe edition
    'Hollywood':
        id: j6em8Baa5Dg
        source: deluxe edition
    'Smoke Signals':
        id: TOQDppcjB-c
        source: Apollo Edition
    'When I Find Love Again':
        id: 7LJOzIrNRMc
        source: Apollo Edition
    'Breathe':
        id: PBfb_C1vb3I
        source: Apollo Edition
    'Trail of Broken Hearts':
        id: OyAqb6aUUd4
        source: Apollo Edition
    'Working It Out':
        id: 6pu9jeiJwUg
        source: Apollo Edition
    "Next Time I'm Seventeen":
        id: 0LvbBNq_gz8
        source: B-side of "Bonfire Heart"
    'Heroes':
        id: uByk9ScQKFo
        source: B-side of "Bonfire Heart"
    "I Guess That's Why They Call It the Blues":
        id: 2XGRM9b5ncE
        cover: Elton John
        source: 'BBC Radio 2: Sounds of the 80s'

'The Afterlove':
    'Love Me Better':
        id: isK2g5ZGJBg
    'Bartender':
        id: ZLClCNY6KpQ
    'Lose My Number':
        id: fwckRBYB0FQ
    "Don't Give Me Those Eyes":
        id: afn932s4xF8
    'Someone Singing Along':
        id: XiP_lkMila4
    'California':
        id: IS9jyTFfEXg
    'Make Me Better':
        id: N12lUcqYUL0
    'Time of Our Lives':
        id: QeIK7OeoKFc
    'Heartbeat':
        id: egwr4PNDBQM
    'Paradise':
        id: UliRcD0FEAI
    "Courtney's Song":
        id: ahlamr7jE4M
        source: extended version
    '2005':
        id: orS6b4YQGPs
        source: extended version
    'Over':
        id: qBeR8byJy3w
        source: extended version
    'OK':
        id: 9kxQ7GFngTA
        live: Ed Sheeran Tour, Tampa, 2017
        source: single by Robin Schulz
    'Bridge over Troubled Water':
        id: z3eGS78gRCE
        cover: Simon & Garfunkel
        source: Artists for Grenfell Tower charity single
    'Melody':
        id: GdhSz6Kfiys
        source: single by Lost Frequencies
    'Walk Away':
        id: eF6YMwfMVYs
        source: single by Alle Farben

'Once Upon a Mind':
    'The Truth':
        id: EaQvOQnd3p4
    'Cold':
        id: uv3a_9vuZVw
    'Champions':
        id: 0ZC5PdwjoAc
    'Monsters':
        id: bGMPohATVr4
    'Youngster':
        id: Wdew_dP_BiY
    '5 Miles':
        id: -6ooOSVcFGU
    'How It Feels to Be Alive':
        id: CUCTsHS0R4o
    'I Told You':
        id: wrfW5ah71VU
    'Halfway':
        id: jwZgkCVk8nQ
    'Stop the Clock':
        id: raINhIPR160
    'The Greatest':
        id: hcK2d4hFBWg
    'Should I Give It All Up':
        id: 1JtlfpXRMAE
        source: Time Suspended edition
    'Happier':
        id: 4X6mrJbtmX4
        source: Time Suspended edition
    'Love Under Pressure':
        id: iW39_R-JZl0
        source: '"The Stars Beneath My Feet (2004–2021)" compilation album'
    'Adrenaline':
        id: Tzzgmnz9hXM
        source: '"The Stars Beneath My Feet (2004–2021)" compilation album'
    'Unstoppable':
        id: sFRtMtsFHRA
        source: '"The Stars Beneath My Feet (2004–2021)" compilation album'
    'I Came for Love':
        id: NtKnm0FdT8U
        source: '"The Stars Beneath My Feet (2004–2021)" compilation album'
    "Can't Forget You":
        id: todcvHFHn3c
        source: single by James Carter & Ofenbach

'Who We Used to Be':
    'Saving a Life':
        id: GuPWq-d6U0U
    'Some Kind of Beautiful':
        id: RI0HJhmhJiQ
    'Beside You':
        id: O4ce48whOo0
    'Last Dance':
        id: 1OAG4-eT9Gk
    'All the Love That I Ever Needed':
        id: StahDvuzb5w
    'The Girl That Never Was':
        id: NO0W5o5VWYE
    'Cold Shoulder':
        id: --hVkcGyWlI
    "I Won't Die with You":
        id: DgMcum5M-0Q
    'Dark Thought':
        id: sFClYIicGOw
    'Glow':
        id: pI2otpEzFBI
    'Confetti and Roses':
        id: CzteHhr7_TQ
        source: deluxe edition
    'Care a Little Less':
        id: depku1_U_dQ
        source: deluxe edition
    'A Thousand Lives':
        id: McxM4cCpbrc
        source: deluxe edition
    "When You're Gone":
        id: BE34fuedcDg
        source: deluxe edition
